# Generated by Django 3.1 on 2021-01-17 03:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Airline_Company',
            fields=[
                ('CID', models.AutoField(primary_key=True, serialize=False)),
                ('COMPANY_NAME', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AIRPLANE',
            fields=[
                ('AIRPLANE_NUMBER', models.IntegerField(primary_key=True, serialize=False)),
                ('MODEL', models.CharField(max_length=10)),
                ('SEAT_CAPACITY', models.IntegerField()),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.airline_company')),
            ],
        ),
        migrations.CreateModel(
            name='AIRPORT',
            fields=[
                ('AIRPORT_CODE', models.CharField(max_length=5, primary_key=True, serialize=False, unique=True)),
                ('AIRPORT_NAME', models.CharField(max_length=100)),
                ('CITY', models.CharField(max_length=30)),
                ('ZIP', models.IntegerField()),
                ('STATE', models.CharField(max_length=30)),
                ('COUNTRY', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='FLIGHT_TRIP',
            fields=[
                ('TRIP_ID', models.AutoField(primary_key=True, serialize=False)),
                ('DEPART_TIME', models.DateTimeField()),
                ('ARIVAL_TIME', models.DateTimeField()),
                ('ARIVAL_AIRPORT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arival', to='bookings.airport')),
                ('DEPARTURE_AIRPORT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination', to='bookings.airport')),
                ('airplane_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.airplane')),
            ],
        ),
        migrations.CreateModel(
            name='USER_INFO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=13)),
                ('profile_pic', models.ImageField(blank=True, upload_to='profile_pics')),
                ('DISCOUNT', models.FloatField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TRANSACTION',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('trip_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookings.flight_trip')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.user_info', to_field='user')),
            ],
        ),
        migrations.CreateModel(
            name='PASSENGER',
            fields=[
                ('PID', models.AutoField(primary_key=True, serialize=False)),
                ('FNAME', models.CharField(max_length=30)),
                ('LNAME', models.CharField(max_length=30)),
                ('PHONE', models.CharField(max_length=15)),
                ('SEX', models.CharField(choices=[('M', 'MALE'), ('F', 'FEMALE')], max_length=1)),
                ('CLASS', models.CharField(choices=[('F', 'FIRST'), ('B', 'BUSINESS'), ('E', 'ECONOMY')], max_length=1)),
                ('airplane_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.airplane')),
                ('trip_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.flight_trip')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='bookings.user_info', to_field='user')),
            ],
        ),
        migrations.CreateModel(
            name='FARE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AMOUNT', models.FloatField(max_length=6)),
                ('DISCOUNT', models.FloatField(default=0, max_length=6)),
                ('TAX', models.FloatField(max_length=6)),
                ('CURRENCY', models.CharField(default='INR', max_length=4)),
                ('trip_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.flight_trip')),
            ],
        ),
        migrations.CreateModel(
            name='ACCESS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airplane_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.airplane')),
                ('airport_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.airport')),
            ],
        ),
        migrations.CreateModel(
            name='SEAT',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('FIRST', models.IntegerField(default=0)),
                ('ECONOMY', models.IntegerField(default=0)),
                ('BUSINESS', models.IntegerField(default=0)),
                ('airplane_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.airplane')),
                ('trip_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.flight_trip')),
            ],
            options={
                'unique_together': {('id', 'trip_id')},
            },
        ),
    ]
