# Generated by Django 3.1 on 2020-12-28 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airline_Company',
            fields=[
                ('CID', models.AutoField(primary_key=True, serialize=False)),
                ('COMPANY_NAME', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AIRPLANE',
            fields=[
                ('AIRPLANE_NUMBER', models.IntegerField(primary_key=True, serialize=False)),
                ('MODEL', models.CharField(max_length=10)),
                ('SEAT_CAPACITY', models.IntegerField()),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.airline_company')),
            ],
        ),
        migrations.CreateModel(
            name='AIRPORT',
            fields=[
                ('AIRPORT_CODE', models.CharField(max_length=5, primary_key=True, serialize=False, unique=True)),
                ('AIRPORT_NAME', models.CharField(max_length=100)),
                ('CITY', models.CharField(max_length=30)),
                ('ZIP', models.IntegerField()),
                ('STATE', models.CharField(max_length=30)),
                ('COUNTRY', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('UID', models.AutoField(primary_key=True, serialize=False)),
                ('FNAME', models.CharField(max_length=30)),
                ('LNAME', models.CharField(max_length=30)),
                ('EMAIL', models.EmailField(max_length=100, unique=True)),
                ('PHONE', models.CharField(max_length=12, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SEAT',
            fields=[
                ('SEAT_NUMBER', models.AutoField(primary_key=True, serialize=False)),
                ('CLASS', models.CharField(max_length=10)),
                ('AVAILABILITY', models.BooleanField()),
                ('airplane_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.airplane')),
            ],
        ),
        migrations.CreateModel(
            name='PASSENGER',
            fields=[
                ('PID', models.AutoField(primary_key=True, serialize=False)),
                ('FNAME', models.CharField(max_length=30)),
                ('LNAME', models.CharField(max_length=30)),
                ('PHONE', models.CharField(max_length=12)),
                ('seat_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.airplane')),
            ],
        ),
        migrations.CreateModel(
            name='FLIGHT_TRIP',
            fields=[
                ('TRIP_ID', models.AutoField(primary_key=True, serialize=False)),
                ('DEPART_TIME', models.DateTimeField()),
                ('ARIVAL_TIME', models.DateTimeField()),
                ('ARIVAL_AIRPORT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arival', to='bookings.airport')),
                ('DESTINATION_AIRPORT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination', to='bookings.airport')),
                ('airplane_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.airplane')),
            ],
        ),
        migrations.CreateModel(
            name='FARE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AMOUNT', models.FloatField(max_length=6)),
                ('DISCOUNT', models.FloatField(default=0, max_length=6)),
                ('TAX', models.FloatField(max_length=6)),
                ('CURRENCY', models.CharField(max_length=4)),
                ('trip_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.flight_trip')),
            ],
        ),
        migrations.CreateModel(
            name='ACCESS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airplane_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.airplane')),
                ('airport_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.airport')),
            ],
        ),
    ]
