# Generated by Django 3.1 on 2021-01-17 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passenger',
            old_name='userId',
            new_name='user',
        ),
    ]
