# Generated by Django 3.1 on 2020-12-30 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_auto_20201230_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='SEX',
            field=models.CharField(choices=[('M', 'MALE'), ('F', 'FEMALE')], max_length=1),
        ),
    ]
