# Generated by Django 3.1 on 2021-01-17 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_auto_20210117_0918'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fare',
            name='DISCOUNT',
        ),
    ]
