# Generated by Django 3.1 on 2020-12-28 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_auto_20201228_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.RESTRICT, to='bookings.user_info'),
        ),
    ]
