# Generated by Django 3.1 on 2021-01-07 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_auto_20201230_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='CLASS',
            field=models.CharField(choices=[('F', 'FIRST'), ('B', 'BUSINESS'), ('E', 'ECONOMY')], default='E', max_length=1),
            preserve_default=False,
        ),
    ]
