# Generated by Django 3.1 on 2021-01-07 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_passenger_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='PHONE',
            field=models.CharField(max_length=12),
        ),
    ]
