# Generated by Django 3.1 on 2021-01-08 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_auto_20210107_1832'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flight_trip',
            old_name='DESTINATION_AIRPORT',
            new_name='DEPARTURE_AIRPORT',
        ),
        migrations.AlterField(
            model_name='passenger',
            name='PHONE',
            field=models.CharField(max_length=15),
        ),
    ]
