# Generated by Django 3.1 on 2021-01-12 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0009_auto_20210112_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='bookings.user_info', to_field='user'),
        ),
    ]
